// Code generated by Sqltom. DO NOT EDIT.

package {{ $.Table.PackageName }}

import ({{ range $.Imports }}
	{{ if ne .Qualifier "" }}{{ .Qualifier }} {{ end }}{{ quote .Path }}{{ end }}
)

{{- $structName := $.Table.GoName }}

{{ if or $.ScanJSON $.ScanBoolean $.ScanTime $.ScanUUID $.ScanBinary }}
// {{ $.Names.scanValue }} adapts logical values before the standard SQL conversion.
type {{ $.Names.scanValue }} struct {
	destination any
	kind string
}

func ({{ $.Names.s }} {{ $.Names.scanValue }}) Scan({{ $.Names.value }} any) error {
	switch {{ $.Names.s }}.kind {
	{{ if $.ScanJSON }}case "json":
		if {{ $.Names.converted }}, ok := {{ $.Names.value }}.(string); ok {
			{{ $.Names.value }} = []byte({{ $.Names.converted }})
		}
	{{ end }}{{ if $.ScanBoolean }}case "boolean":
		if {{ $.Names.bytes }}, ok := {{ $.Names.value }}.([]byte); ok && len({{ $.Names.bytes }}) == 1 && {{ $.Names.bytes }}[0] <= 1 {
			{{ $.Names.value }} = {{ $.Names.bytes }}[0] == 1
		}
	{{ end }}{{ if $.ScanBinary }}case "binary":
		// A typed nil byte slice from SQLite is an empty BLOB; SQL NULL is nil.
		if {{ $.Names.bytes }}, ok := {{ $.Names.value }}.([]byte); ok && {{ $.Names.bytes }} == nil {
			{{ $.Names.value }} = []byte{}
		}
	{{ end }}{{ if $.ScanTime }}case "time":
		if {{ $.Names.converted }}, ok := {{ $.Names.value }}.({{ $.Names.time }}.Time); ok {
			{{ $.Names.value }} = {{ $.Names.converted }}.Format("15:04:05.999999999")
		}
	{{ end }}{{ if $.ScanUUID }}case "uuid":
		{{ if $.ScanSQLServerUUID }}
		if {{ $.Names.value }} != nil {
			// Decode SQL Server's native UUID byte order exactly once. Canonical
			// text is accepted by both the driver codec and application Scanners.
			if {{ $.Names.bytes }}, ok := {{ $.Names.value }}.([]byte); ok && len({{ $.Names.bytes }}) != 16 {
				{{ $.Names.value }} = string({{ $.Names.bytes }})
			}
			var {{ $.Names.converted }} {{ $.Names.mssql }}.UniqueIdentifier
			if {{ $.Names.err }} := {{ $.Names.converted }}.Scan({{ $.Names.value }}); {{ $.Names.err }} != nil {
				return {{ $.Names.err }}
			}
			{{ $.Names.value }} = {{ $.Names.converted }}.String()
		}
		{{ end }}
		switch {{ $.Names.converted }} := {{ $.Names.value }}.(type) {
		case string:
			{{ $.Names.value }} = {{ $.Names.strings }}.ToLower({{ $.Names.converted }})
		case []byte:
			{{ $.Names.value }} = {{ $.Names.strings }}.ToLower(string({{ $.Names.converted }}))
		}
	{{ end }}}
	return sql.ConvertAssign({{ $.Names.driver }}.ScanContext{}, {{ $.Names.s }}.destination, {{ $.Names.value }})
}
{{ end }}

{{ if $.JSONArguments }}
// {{ $.Names.jsonValue }} sends JSON as text, including on drivers that bind []byte as binary.
type {{ $.Names.jsonValue }} struct { value any }

func ({{ $.Names.a }} {{ $.Names.jsonValue }}) Value() ({{ $.Names.driver }}.Value, error) {
	{{ $.Names.value }}, {{ $.Names.err }} := {{ $.Names.driver }}.DefaultParameterConverter.ConvertValue({{ $.Names.a }}.value)
	if {{ $.Names.err }} != nil { return nil, {{ $.Names.err }} }
	if {{ $.Names.bytes }}, ok := {{ $.Names.value }}.([]byte); ok {
		if {{ $.Names.bytes }} == nil { return nil, nil }
		return string({{ $.Names.bytes }}), nil
	}
	return {{ $.Names.value }}, nil
}
{{ end }}

{{ if $.UUIDArguments }}
// {{ $.Names.uuidValue }} binds string UUIDs in lowercase, preserving SQL NULL.
func {{ $.Names.uuidValue }}({{ $.Names.value }} *string) any {
	if {{ $.Names.value }} == nil { return nil }
	return {{ $.Names.strings }}.ToLower(*{{ $.Names.value }})
}
{{ end }}

{{ if $.BinaryArguments }}
// {{ $.Names.binaryValue }} preserves the binary SQL type for NULL parameters.
func {{ $.Names.binaryValue }}({{ $.Names.value }} *[]byte) []byte {
	if {{ $.Names.value }} == nil { return nil }
	return *{{ $.Names.value }}
}
{{ end }}

// DBTX is implemented by both *sql.DB and *sql.Tx.
type DBTX interface {
	Exec({{ $.Names.query }} string, {{ $.Names.args }} ...interface{}) (sql.Result, error)
	Query({{ $.Names.query }} string, {{ $.Names.args }} ...interface{}) (*sql.Rows, error)
	QueryRow({{ $.Names.query }} string, {{ $.Names.args }} ...interface{}) *sql.Row
}

{{- $structType := "table" -}}
{{- if eq $.Table.TableType "VIEW" -}}
	{{- $structType = "view" -}}
{{- end }}

// {{ $structName }} defines a row in {{ quote $.Table.TableName }} {{ $structType }}.
type {{ $structName }} struct {
{{- range $.Table.Columns }}
	{{ .GoName }} {{ .ResolvedGoType }} {{ structTag .ColumnName .JSONName .IncludeJSONTag }}
{{- end }}
	// Partial reads cannot be written through full-row Insert or Update.
	{{ $.Names.partial }} bool
}

// Rows holds model pointers in the order returned by the query.
type Rows []*{{ $structName }}

// ErrMultipleRows means One found more than one loaded row.
var ErrMultipleRows = {{ $.Names.errors }}.New("expected exactly one row")

// ErrIndexOutOfRange means At received an index outside the loaded rows.
var ErrIndexOutOfRange = {{ $.Names.errors }}.New("row index out of range")

// First returns the first loaded row, or sql.ErrNoRows when empty.
func ({{ $.Names.rows }} Rows) First() (*{{ $structName }}, error) {
	if len({{ $.Names.rows }}) == 0 { return nil, sql.ErrNoRows }
	return {{ $.Names.rows }}[0], nil
}

// Last returns the last loaded row, or sql.ErrNoRows when empty.
func ({{ $.Names.rows }} Rows) Last() (*{{ $structName }}, error) {
	if len({{ $.Names.rows }}) == 0 { return nil, sql.ErrNoRows }
	return {{ $.Names.rows }}[len({{ $.Names.rows }})-1], nil
}

// One returns the only loaded row. Empty results return sql.ErrNoRows;
// multiple rows return an error wrapping ErrMultipleRows.
func ({{ $.Names.rows }} Rows) One() (*{{ $structName }}, error) {
	switch len({{ $.Names.rows }}) {
	case 0:
		return nil, sql.ErrNoRows
	case 1:
		return {{ $.Names.rows }}[0], nil
	default:
		return nil, {{ $.Names.fmt }}.Errorf("%w: got %d", ErrMultipleRows, len({{ $.Names.rows }}))
	}
}

// At returns the loaded row at a zero-based index, or an error wrapping
// ErrIndexOutOfRange for a negative index or an index >= len(rows).
func ({{ $.Names.rows }} Rows) At({{ $.Names.index }} int) (*{{ $structName }}, error) {
	if {{ $.Names.index }} < 0 || {{ $.Names.index }} >= len({{ $.Names.rows }}) {
		return nil, {{ $.Names.fmt }}.Errorf("%w: index %d, length %d", ErrIndexOutOfRange, {{ $.Names.index }}, len({{ $.Names.rows }}))
	}
	return {{ $.Names.rows }}[{{ $.Names.index }}], nil
}

// IsEmpty reports whether the loaded collection has no rows, including a nil slice.
func ({{ $.Names.rows }} Rows) IsEmpty() bool {
	return len({{ $.Names.rows }}) == 0
}

// Filter returns a new slice containing the existing pointers that satisfy
// predicate, preserving their order. It does not modify the source slice or
// query the database. With no matches it returns a non-nil empty Rows.
// The predicate is called once per element, including any manually added nil
// pointers, and must be non-nil. A nil predicate panics even on an empty slice.
func ({{ $.Names.rows }} Rows) Filter({{ $.Names.predicate }} func(*{{ $structName }}) bool) Rows {
	if {{ $.Names.predicate }} == nil { panic("Rows.Filter: nil predicate") }
	{{ $.Names.result }} := Rows{}
	for _, {{ $.Names.row }} := range {{ $.Names.rows }} {
		if {{ $.Names.predicate }}({{ $.Names.row }}) {
			{{ $.Names.result }} = append({{ $.Names.result }}, {{ $.Names.row }})
		}
	}
	return {{ $.Names.result }}
}

// SelectAll selects all model columns using the statement suffix.
// Use ORDER BY in the suffix when row order matters.
func SelectAll({{ $.Names.db }} DBTX, {{ $.Names.stmt }} string, {{ $.Names.args }} ...interface{}) (Rows, error) {
	var {{ $.Names.query }} = `SELECT ` +
		`{{- range $i, $e := $.Table.Columns }}
			{{ sqlIdentifier $.Table.TableName }}.{{ sqlIdentifier .ColumnName }}{{ if last $i $.Table.Columns | not }}, {{ end }}
		{{- end }} ` +
		`FROM {{ sqlTableIdentifier $.Table.TableCatalog $.Table.TableSchema $.Table.TableName }} ` + {{ $.Names.stmt }}

	return Query({{ $.Names.db }}, {{ $.Names.query }}, {{ $.Names.args }}...)
}

// SelectCols inserts projection verbatim into SELECT, followed by the statement suffix.
// Use trusted SQL with the dialect's quoting; expressions must have aliases matching
// database column names in the manifest. Result names must be unique and known.
// Unselected fields retain their Go zero values. A partially loaded row cannot be
// passed to Insert or Update. Selecting every model column produces a complete row.
func SelectCols({{ $.Names.db }} DBTX, {{ $.Names.projection }} string, {{ $.Names.stmt }} string, {{ $.Names.args }} ...interface{}) (Rows, error) {
	{{ $.Names.query }} := "SELECT " + {{ $.Names.projection }} + ` FROM {{ sqlTableIdentifier $.Table.TableCatalog $.Table.TableSchema $.Table.TableName }} ` + {{ $.Names.stmt }}
	{{ $.Names.rows }}, {{ $.Names.err }} := {{ $.Names.db }}.Query({{ $.Names.query }}, {{ $.Names.args }}...)
	if {{ $.Names.err }} != nil { return nil, {{ $.Names.err }} }
	defer {{ $.Names.rows }}.Close()
	{{ $.Names.columns }}, {{ $.Names.err }} := {{ $.Names.rows }}.Columns()
	if {{ $.Names.err }} != nil { return nil, {{ $.Names.err }} }
	if len({{ $.Names.columns }}) == 0 {
		return nil, {{ $.Names.fmt }}.Errorf("SelectCols: no result columns")
	}
	{{ $.Names.indexes }} := make([]int, len({{ $.Names.columns }}))
	{{ $.Names.seen }} := make(map[string]bool, len({{ $.Names.columns }}))
	for {{ $.Names.index }}, {{ $.Names.column }} := range {{ $.Names.columns }} {
		if {{ $.Names.seen }}[{{ $.Names.column }}] {
			return nil, {{ $.Names.fmt }}.Errorf("SelectCols: duplicate result column %q", {{ $.Names.column }})
		}
		{{ $.Names.seen }}[{{ $.Names.column }}] = true
		switch {{ $.Names.column }} {
		{{- range $i, $e := $.Table.Columns }}
		case {{ quote .ColumnName }}:
			{{ $.Names.indexes }}[{{ $.Names.index }}] = {{ $i }}
		{{- end }}
		default:
			return nil, {{ $.Names.fmt }}.Errorf("SelectCols: unknown result column %q", {{ $.Names.column }})
		}
	}
	{{ $.Names.result }} := Rows{}
	{{ $.Names.destinations }} := make([]any, len({{ $.Names.indexes }}))
	for {{ $.Names.rows }}.Next() {
		{{ $.Names.r }} := &{{ $structName }}{ {{ $.Names.partial }}: len({{ $.Names.columns }}) < {{ len $.Table.Columns }} }
		for {{ $.Names.index }}, {{ $.Names.column }} := range {{ $.Names.indexes }} {
			switch {{ $.Names.column }} {
			{{- range $i, $e := $.Table.Columns }}
			case {{ $i }}:
				{{ $.Names.destinations }}[{{ $.Names.index }}] = {{ if .ScanKind }}{{ $.Names.scanValue }}{destination: &{{ $.Names.r }}.{{ .GoName }}, kind: {{ quote .ScanKind }}}{{ else }}&{{ $.Names.r }}.{{ .GoName }}{{ end }}
			{{- end }}
			}
		}
		if {{ $.Names.err }} := {{ $.Names.rows }}.Scan({{ $.Names.destinations }}...); {{ $.Names.err }} != nil { return nil, {{ $.Names.err }} }
		{{ $.Names.result }} = append({{ $.Names.result }}, {{ $.Names.r }})
	}
	if {{ $.Names.err }} := {{ $.Names.rows }}.Err(); {{ $.Names.err }} != nil { return nil, {{ $.Names.err }} }
	return {{ $.Names.result }}, nil
}

{{- if eq $.Table.TableType "BASE TABLE" }}

// Insert inserts the row into the database.
func ({{ $.Names.r }} *{{ $structName }}) Insert({{ $.Names.db }} DBTX) error {
	if {{ $.Names.r }}.{{ $.Names.partial }} {
		return {{ $.Names.fmt }}.Errorf("cannot insert a partially loaded row; use SelectAll first")
	}
	{{- $hasWriteColumns := gt (len $.Table.WriteColumns) 0 }}
	{{- $hasIdentity := gt (len $.IdentityColumns) 0 }}
	const {{ $.Names.query }} =
		{{- if and $hasIdentity (eq $.InsertStrategy "scope-identity") }}
		`SET NOCOUNT ON; ` +
		{{- end }}
		`INSERT INTO {{ sqlTableIdentifier $.Table.TableCatalog $.Table.TableSchema $.Table.TableName }}` +
		{{- if $hasWriteColumns }}
		` (` +
		`{{- range $i, $e := $.Table.WriteColumns }}
			{{ sqlIdentifier .ColumnName }}{{ if last $i $.Table.WriteColumns | not }}, {{ end }}
		{{- end -}}` +
		`) VALUES (` +
		{{- $c := 0 }}
		`{{- range $i, $e := $.Table.WriteColumns }}
			{{- $c = add $c 1 -}}
			{{ placeholder $c }}{{ if last $i $.Table.WriteColumns | not }}, {{ end }}
		{{- end -}}` +
		`)`
		{{- else }}
		` {{ $.EmptyInsert }}`
		{{- end }}
		{{- if and $hasIdentity (eq $.InsertStrategy "returning") }} +
		` RETURNING {{ range $i, $e := $.IdentityColumns }}{{ sqlIdentifier .ColumnName }}{{ if last $i $.IdentityColumns | not }}, {{ end }}{{ end }}`
		{{- end }}
		{{- if and $hasIdentity (eq $.InsertStrategy "scope-identity") }} +
		`; SELECT SCOPE_IDENTITY()`
		{{- end }}

	{{- if $hasIdentity }}
		{{- if eq $.InsertStrategy "returning" }}
	{{ $.Names.row }} := {{ $.Names.db }}.QueryRow(
		{{ $.Names.query }},
		{{- range $.Table.WriteColumns }}
		{{ if .IsJSON }}{{ $.Names.jsonValue }}{value: {{ $.Names.r }}.{{ .GoName }}},{{ else if .IsUUIDString }}{{ $.Names.uuidValue }}({{ if eq .ResolvedGoType "string" }}&{{ end }}{{ $.Names.r }}.{{ .GoName }}),{{ else if and $.BinaryArguments .IsBinaryBytes (eq .ResolvedGoType "*[]byte") }}{{ $.Names.binaryValue }}({{ $.Names.r }}.{{ .GoName }}),{{ else }}{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
	)
	if {{ $.Names.err }} := {{ $.Names.row }}.Scan(
		{{- range $.IdentityColumns }}
		{{ if .ScanKind }}{{ $.Names.scanValue }}{destination: &{{ $.Names.r }}.{{ .GoName }}, kind: {{ quote .ScanKind }}},{{ else }}&{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
	); {{ $.Names.err }} != nil {
		return {{ $.Names.err }}
	}
		{{- else if eq $.InsertStrategy "scope-identity" }}
			{{- $identity := index $.IdentityColumns 0 }}
	{{ $.Names.row }} := {{ $.Names.db }}.QueryRow(
		{{ $.Names.query }},
		{{- range $.Table.WriteColumns }}
		{{ if .IsJSON }}{{ $.Names.jsonValue }}{value: {{ $.Names.r }}.{{ .GoName }}},{{ else if .IsUUIDString }}{{ $.Names.uuidValue }}({{ if eq .ResolvedGoType "string" }}&{{ end }}{{ $.Names.r }}.{{ .GoName }}),{{ else if and $.BinaryArguments .IsBinaryBytes (eq .ResolvedGoType "*[]byte") }}{{ $.Names.binaryValue }}({{ $.Names.r }}.{{ .GoName }}),{{ else }}{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
	)
	if {{ $.Names.err }} := {{ $.Names.row }}.Scan(&{{ $.Names.r }}.{{ $identity.GoName }}); {{ $.Names.err }} != nil {
		return {{ $.Names.err }}
	}
		{{- else }}
			{{- $identity := index $.IdentityColumns 0 }}
	{{ $.Names.result }}, {{ $.Names.err }} := {{ $.Names.db }}.Exec(
		{{ $.Names.query }},
		{{- range $.Table.WriteColumns }}
		{{ if .IsJSON }}{{ $.Names.jsonValue }}{value: {{ $.Names.r }}.{{ .GoName }}},{{ else if .IsUUIDString }}{{ $.Names.uuidValue }}({{ if eq .ResolvedGoType "string" }}&{{ end }}{{ $.Names.r }}.{{ .GoName }}),{{ else if and $.BinaryArguments .IsBinaryBytes (eq .ResolvedGoType "*[]byte") }}{{ $.Names.binaryValue }}({{ $.Names.r }}.{{ .GoName }}),{{ else }}{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
	)
	if {{ $.Names.err }} != nil {
		return {{ $.Names.err }}
	}
	{{ $.Names.lastInsertID }}, {{ $.Names.err }} := {{ $.Names.result }}.LastInsertId()
	if {{ $.Names.err }} != nil {
		return {{ $.Names.err }}
	}
	{{- if $.UnsignedLastInsertID }}
	var {{ $.Names.identityValue }} any = {{ $.Names.lastInsertID }}
	if {{ $.Names.lastInsertID }} < 0 {
		// MySQL preserves unsigned identity bits in LastInsertId's int64.
		// Decimal text is a driver.Value and retains checked Scanner conversion.
		{{ $.Names.identityValue }} = {{ $.Names.strconv }}.FormatUint(uint64({{ $.Names.lastInsertID }}), 10)
	}
	{{- end }}
	if {{ $.Names.err }} := sql.ConvertAssign({{ $.Names.driver }}.ScanContext{}, &{{ $.Names.r }}.{{ $identity.GoName }}, {{ if $.UnsignedLastInsertID }}{{ $.Names.identityValue }}{{ else }}{{ $.Names.lastInsertID }}{{ end }}); {{ $.Names.err }} != nil {
		return {{ $.Names.err }}
	}
		{{- end }}
	{{- else }}
	_, {{ $.Names.err }} := {{ $.Names.db }}.Exec(
		{{ $.Names.query }},
		{{- range $.Table.WriteColumns }}
		{{ if .IsJSON }}{{ $.Names.jsonValue }}{value: {{ $.Names.r }}.{{ .GoName }}},{{ else if .IsUUIDString }}{{ $.Names.uuidValue }}({{ if eq .ResolvedGoType "string" }}&{{ end }}{{ $.Names.r }}.{{ .GoName }}),{{ else if and $.BinaryArguments .IsBinaryBytes (eq .ResolvedGoType "*[]byte") }}{{ $.Names.binaryValue }}({{ $.Names.r }}.{{ .GoName }}),{{ else }}{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
	)
	if {{ $.Names.err }} != nil {
		return {{ $.Names.err }}
	}
	{{- end }}

	return nil
}

{{- if and (gt (len $.Table.KeyColumns) 0) (gt (len $.Table.UpdateColumns) 0) }}

// Update updates the row in the database using its complete key.
func ({{ $.Names.r }} *{{ $structName }}) Update({{ $.Names.db }} DBTX) error {
	if {{ $.Names.r }}.{{ $.Names.partial }} {
		return {{ $.Names.fmt }}.Errorf("cannot update a partially loaded row; use SelectAll first")
	}
	{{- if $.RejectNullUpdateKey }}
	// A NULL primary key cannot uniquely identify a SQLite row. Convert once,
	// check SQL NULL (including a nil byte slice), and reuse the bound values.
	{{ $.Names.keyArgs }} := []any{
		{{- range $.Table.KeyColumns }}
		{{ if .IsJSON }}{{ $.Names.jsonValue }}{value: {{ $.Names.r }}.{{ .GoName }}},{{ else if .IsUUIDString }}{{ $.Names.uuidValue }}({{ if eq .ResolvedGoType "string" }}&{{ end }}{{ $.Names.r }}.{{ .GoName }}),{{ else if and $.BinaryArguments .IsBinaryBytes (eq .ResolvedGoType "*[]byte") }}{{ $.Names.binaryValue }}({{ $.Names.r }}.{{ .GoName }}),{{ else }}{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
	}
	{{ $.Names.keyNames }} := [...]string{ {{ range $.Table.KeyColumns }}{{ quote .ColumnName }}, {{ end }} }
	for {{ $.Names.keyIndex }}, {{ $.Names.keyValue }} := range {{ $.Names.keyArgs }} {
		{{ $.Names.value }}, {{ $.Names.err }} := {{ $.Names.driver }}.DefaultParameterConverter.ConvertValue({{ $.Names.keyValue }})
		if {{ $.Names.err }} != nil {
			return {{ $.Names.fmt }}.Errorf("convert primary key %q: %w", {{ $.Names.keyNames }}[{{ $.Names.keyIndex }}], {{ $.Names.err }})
		}
		if {{ $.Names.bytes }}, {{ $.Names.one }} := {{ $.Names.value }}.([]byte); {{ $.Names.value }} == nil || ({{ $.Names.one }} && {{ $.Names.bytes }} == nil) {
			return {{ $.Names.fmt }}.Errorf("cannot update row: primary key %q is NULL", {{ $.Names.keyNames }}[{{ $.Names.keyIndex }}])
		}
		{{ $.Names.keyArgs }}[{{ $.Names.keyIndex }}] = {{ $.Names.value }}
	}
	{{- end }}
	{{- $c := 0 }}
	const {{ $.Names.query }} = `UPDATE {{ sqlTableIdentifier $.Table.TableCatalog $.Table.TableSchema $.Table.TableName }} SET ` +
		`{{- range $i, $e := $.Table.UpdateColumns }}
			{{- $c = add $c 1 -}}
			{{ sqlIdentifier .ColumnName }} = {{ placeholder $c }}{{ if last $i $.Table.UpdateColumns | not }}, {{ end }}
		{{- end }}` +
		` WHERE ` +
		`
		{{- range $i, $e := $.Table.KeyColumns }}
			{{- $c = add $c 1 -}}
			{{ if $i }} AND {{ end }}{{ sqlIdentifier .ColumnName }} = {{ placeholder $c }}
		{{- end }}`

	_, {{ $.Names.err }} := {{ $.Names.db }}.Exec(
		{{ $.Names.query }},
		{{- range $.Table.UpdateColumns }}
		{{ if .IsJSON }}{{ $.Names.jsonValue }}{value: {{ $.Names.r }}.{{ .GoName }}},{{ else if .IsUUIDString }}{{ $.Names.uuidValue }}({{ if eq .ResolvedGoType "string" }}&{{ end }}{{ $.Names.r }}.{{ .GoName }}),{{ else if and $.BinaryArguments .IsBinaryBytes (eq .ResolvedGoType "*[]byte") }}{{ $.Names.binaryValue }}({{ $.Names.r }}.{{ .GoName }}),{{ else }}{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
		{{- range $i, $key := $.Table.KeyColumns }}
		{{ if $.RejectNullUpdateKey }}{{ $.Names.keyArgs }}[{{ $i }}],{{ else if .IsJSON }}{{ $.Names.jsonValue }}{value: {{ $.Names.r }}.{{ .GoName }}},{{ else if .IsUUIDString }}{{ $.Names.uuidValue }}({{ if eq .ResolvedGoType "string" }}&{{ end }}{{ $.Names.r }}.{{ .GoName }}),{{ else if and $.BinaryArguments .IsBinaryBytes (eq .ResolvedGoType "*[]byte") }}{{ $.Names.binaryValue }}({{ $.Names.r }}.{{ .GoName }}),{{ else }}{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
	)
	return {{ $.Names.err }}
}

{{- end }}

// Delete deletes rows from the database using the statement suffix.
func Delete({{ $.Names.db }} DBTX, {{ $.Names.stmt }} string, {{ $.Names.args }} ...interface{}) error {
	var {{ $.Names.query }} = `DELETE FROM {{ sqlTableIdentifier $.Table.TableCatalog $.Table.TableSchema $.Table.TableName }} ` + {{ $.Names.stmt }}

	_, {{ $.Names.err }} := {{ $.Names.db }}.Exec({{ $.Names.query }}, {{ $.Names.args }}...)
	return {{ $.Names.err }}
}

{{- end }}

// Exists reports whether the statement suffix selects at least one row.
func Exists({{ $.Names.db }} DBTX, {{ $.Names.stmt }} string, {{ $.Names.args }} ...interface{}) (bool, error) {
	var {{ $.Names.query }} = `SELECT 1 FROM {{ sqlTableIdentifier $.Table.TableCatalog $.Table.TableSchema $.Table.TableName }} ` + {{ $.Names.stmt }}

	var {{ $.Names.one }} int
	{{ $.Names.err }} := {{ $.Names.db }}.QueryRow({{ $.Names.query }}, {{ $.Names.args }}...).Scan(&{{ $.Names.one }})
	if {{ $.Names.err }} == sql.ErrNoRows {
		return false, nil
	}
	if {{ $.Names.err }} != nil {
		return false, {{ $.Names.err }}
	}
	return true, nil
}

// Query executes the statement and scans rows in model column order.
func Query({{ $.Names.db }} DBTX, {{ $.Names.stmt }} string, {{ $.Names.args }} ...interface{}) (Rows, error) {
	{{ $.Names.rows }}, {{ $.Names.err }} := {{ $.Names.db }}.Query({{ $.Names.stmt }}, {{ $.Names.args }}...)
	if {{ $.Names.err }} != nil {
		return nil, {{ $.Names.err }}
	}
	defer {{ $.Names.rows }}.Close()

	{{ $.Names.result }} := Rows{}
	for {{ $.Names.rows }}.Next() {
		{{ $.Names.r }} := &{{ $structName }}{}
		if {{ $.Names.err }} := {{ $.Names.rows }}.Scan(
		{{- range $.Table.Columns }}
			{{ if .ScanKind }}{{ $.Names.scanValue }}{destination: &{{ $.Names.r }}.{{ .GoName }}, kind: {{ quote .ScanKind }}},{{ else }}&{{ $.Names.r }}.{{ .GoName }},{{ end }}
		{{- end }}
		); {{ $.Names.err }} != nil {
			return nil, {{ $.Names.err }}
		}
		{{ $.Names.result }} = append({{ $.Names.result }}, {{ $.Names.r }})
	}
	if {{ $.Names.err }} := {{ $.Names.rows }}.Err(); {{ $.Names.err }} != nil {
		return nil, {{ $.Names.err }}
	}

	return {{ $.Names.result }}, nil
}
