package render

import (
	"context"
	"embed"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// Compile and test the implementation as ordinary Go, then copy those exact
// sources into each generated output. Consumers have no dependency on sqltom.
//
//go:embed queryruntime/query.go queryruntime/lexer.go
var querySources embed.FS

func renderQueryPackage(ctx context.Context, staging string, config Config) error {
	dialect := strings.ToLower(config.Dialect)
	switch dialect {
	case "postgresql":
		dialect = "postgres"
	case "sql server":
		dialect = "sqlserver"
	}
	switch dialect {
	case "sqlserver", "postgres", "mysql", "sqlite":
	default:
		return fmt.Errorf("unsupported query helper dialect %q", config.Dialect)
	}
	directory := filepath.Join(staging, "query")
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return err
	}
	for _, name := range []string{"query.go", "lexer.go", "dialect.go"} {
		if err := ctx.Err(); err != nil {
			return err
		}
		var source []byte
		if name == "dialect.go" {
			source = []byte(fmt.Sprintf("package query\n\nconst targetDialect = %q\n", dialect))
		} else {
			var err error
			source, err = querySources.ReadFile("queryruntime/" + name)
			if err != nil {
				return err
			}
		}
		source = append([]byte("// Code generated by Sqltom. DO NOT EDIT.\n\n"), source...)
		formatted, err := format.Source(source)
		if err != nil {
			return fmt.Errorf("format %s: %w", name, err)
		}
		if err := os.WriteFile(filepath.Join(directory, name), formatted, 0o644); err != nil {
			return err
		}
	}
	return nil
}
