package dialect_test

import (
	"bytes"
	"context"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/catamat/sqltom/internal/dialect"
	"github.com/catamat/sqltom/internal/dialect/mysql"
	"github.com/catamat/sqltom/internal/dialect/postgres"
	"github.com/catamat/sqltom/internal/dialect/sqlite"
	"github.com/catamat/sqltom/internal/dialect/sqlserver"
)

func TestGeneratedQueryPackageContract(t *testing.T) {
	backends := []struct {
		name    string
		backend dialect.Backend
	}{
		{dialect.Postgres, postgres.New()}, {dialect.MySQL, mysql.New()}, {dialect.SQLite, sqlite.New()}, {dialect.SQLServer, sqlserver.New()},
	}
	var baseline string
	for _, entry := range backends {
		t.Run(entry.name, func(t *testing.T) {
			output := filepath.Join(t.TempDir(), "models")
			document := runtimeManifest()
			if err := entry.backend.Render(context.Background(), document, output); err != nil {
				t.Fatal(err)
			}
			directory := filepath.Join(output, "query")
			files := token.NewFileSet()
			parsed := []*ast.File{}
			for _, name := range []string{"query.go", "lexer.go", "dialect.go"} {
				source, err := os.ReadFile(filepath.Join(directory, name))
				if err != nil {
					t.Fatal(err)
				}
				if !bytes.HasPrefix(source, []byte("// Code generated by Sqltom.")) {
					t.Fatal("query source is not marked generated")
				}
				if name == "dialect.go" && !strings.Contains(string(source), `const targetDialect = "`+entry.name+`"`) {
					t.Fatalf("wrong helper dialect: %s", source)
				}
				file, err := parser.ParseFile(files, name, source, parser.AllErrors)
				if err != nil {
					t.Fatal(err)
				}
				if file.Name.Name != "query" {
					t.Fatal("wrong package name")
				}
				parsed = append(parsed, file)
			}
			config := types.Config{Importer: importer.Default()}
			if _, err := config.Check("generated.test/query", files, parsed, nil); err != nil {
				t.Fatalf("standalone helper does not compile: %v", err)
			}
			surface := exportedSurface(t, filepath.Join(directory, "query.go"))
			if baseline == "" {
				baseline = surface
			} else if surface != baseline {
				t.Fatalf("query API differs for %s:\n%s", entry.name, surface)
			}
			// Collisions must fail before replacing any previous managed output.
			original, err := os.ReadFile(filepath.Join(directory, "query.go"))
			if err != nil {
				t.Fatal(err)
			}
			for _, name := range []string{"query", "Query", "QUERY", "qUeRy"} {
				document.Tables[0].FileName = name
				err := entry.backend.Render(context.Background(), document, output)
				if err == nil || !strings.Contains(err.Error(), "conflicts with generated support package query") {
					t.Fatalf("collision %q: %v", name, err)
				}
				preserved, err := os.ReadFile(filepath.Join(directory, "query.go"))
				if err != nil {
					t.Fatal(err)
				}
				if !bytes.Equal(preserved, original) {
					t.Fatal("collision replaced existing output")
				}
			}
			document.Tables[0].FileName = "Vehicle"
			document.Tables[0].PackageName = "query" // Package declarations in distinct directories are independent.
			if err := entry.backend.Render(context.Background(), document, output); err != nil {
				t.Fatal(err)
			}
		})
	}
}
