//go:build integration

package integration_test

import (
	"context"
	"database/sql"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/catamat/sqltom/internal/cli"
	"github.com/catamat/sqltom/internal/dialect"
	"github.com/catamat/sqltom/internal/dialect/mysql"
	"github.com/catamat/sqltom/internal/dialect/postgres"
	"github.com/catamat/sqltom/internal/dialect/sqlite"
	"github.com/catamat/sqltom/internal/dialect/sqlserver"
	"github.com/catamat/sqltom/internal/manifest"
)

type fixture struct {
	name       string
	driverName string
	dsn        string
	adminDSN   string
	backend    dialect.Backend
	schema     string
	setup      []string
	returnsID  bool
	selectRow  string
}

func TestAllDialectsUseTheSameInspectionAndRenderingContract(t *testing.T) {
	for _, current := range integrationFixtures(t) {
		t.Run(current.name, func(t *testing.T) {
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
			defer cancel()

			if current.name == dialect.SQLServer {
				prepareSQLServerDatabase(t, ctx, current.adminDSN)
			}
			prepareSchema(t, ctx, current)

			directory := t.TempDir()
			runner := cli.NewWithDependencies(cli.Dependencies{
				WorkingDirectory: directory,
				Backends:         map[string]dialect.Backend{current.name: current.backend},
			})
			result, err := runner.Generate(ctx, current.name, current.dsn, filepath.Join(directory, "models"), nil)
			if err != nil {
				t.Fatalf("Generate() error = %v", err)
			}

			document, err := manifest.Load(result.ManifestFilename)
			if err != nil {
				t.Fatal(err)
			}
			assertCommonManifest(t, document, current)
			modelFilename := filepath.Join(directory, "models", "Vehicle", "Vehicle.go")
			assertCommonRenderedWrites(t, modelFilename)
			executeCommonRenderedWrites(t, ctx, current, modelFilename)
			if current.name == dialect.Postgres {
				assertPostgresDomainDefault(t, ctx, current)
			}
		})
	}
}

func integrationFixtures(t *testing.T) []fixture {
	t.Helper()
	requireExternal := os.Getenv("SQLTOM_REQUIRE_EXTERNAL_DATABASES") == "1"
	requiredDSN := func(name string) string {
		t.Helper()
		value := os.Getenv(name)
		if value == "" && requireExternal {
			t.Fatalf("%s is required by SQLTOM_REQUIRE_EXTERNAL_DATABASES", name)
		}
		return value
	}

	sqliteFilename := filepath.Join(t.TempDir(), "sqltom_test.db")
	sqliteDB, err := sql.Open(dialect.SQLite, sqliteFilename)
	if err != nil {
		t.Fatal(err)
	}
	if err := sqliteDB.Close(); err != nil {
		t.Fatal(err)
	}

	fixtures := []fixture{
		{
			name:       dialect.SQLServer,
			driverName: dialect.SQLServer,
			dsn:        requiredDSN("SQLTOM_SQLSERVER_DSN"),
			adminDSN:   requiredDSN("SQLTOM_SQLSERVER_ADMIN_DSN"),
			backend:    sqlserver.New(),
			schema:     "dbo",
			returnsID:  true,
			selectRow:  `SELECT [Name], [Defaulted], [Slug], [Notes] FROM [dbo].[Vehicle] WHERE [ID] = @p1`,
			setup: []string{
				`IF OBJECT_ID(N'dbo.VehicleView', N'V') IS NOT NULL DROP VIEW dbo.VehicleView`,
				`IF OBJECT_ID(N'dbo.Vehicle', N'U') IS NOT NULL DROP TABLE dbo.Vehicle`,
				`IF OBJECT_ID(N'dbo.CompositeKey', N'U') IS NOT NULL DROP TABLE dbo.CompositeKey`,
				`CREATE TABLE dbo.Vehicle (
					[Name] nvarchar(100) NOT NULL,
					[ID] int IDENTITY(1,1) NOT NULL CONSTRAINT PK_Vehicle PRIMARY KEY,
					[Defaulted] nvarchar(100) NULL CONSTRAINT DF_Vehicle_Defaulted DEFAULT N'default',
					[Slug] AS LOWER([Name]) PERSISTED,
					[Notes] nvarchar(100) NULL
				)`,
				`CREATE VIEW dbo.VehicleView AS
				 SELECT [Name], [ID], [Defaulted], [Slug], [Notes] FROM dbo.Vehicle`,
				`CREATE TABLE dbo.CompositeKey (
					[TenantID] int NOT NULL,
					[ItemID] int NOT NULL,
					[Payload] nvarchar(100) NULL,
					CONSTRAINT PK_CompositeKey PRIMARY KEY ([TenantID], [ItemID])
				)`,
			},
		},
		{
			name:       dialect.Postgres,
			driverName: "pgx",
			dsn:        requiredDSN("SQLTOM_POSTGRES_DSN"),
			backend:    postgres.New(),
			schema:     "public",
			returnsID:  true,
			selectRow:  `SELECT "Name", "Defaulted", "Slug", "Notes" FROM "public"."Vehicle" WHERE "ID" = $1`,
			setup: []string{
				`DROP VIEW IF EXISTS "VehicleView"`,
				`DROP TABLE IF EXISTS "Vehicle"`,
				`DROP TABLE IF EXISTS "CompositeKey"`,
				`CREATE TABLE "Vehicle" (
					"Name" text NOT NULL,
					"ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					"Defaulted" text DEFAULT 'default',
					"Slug" text GENERATED ALWAYS AS (lower("Name")) STORED,
					"Notes" text
				)`,
				`CREATE VIEW "VehicleView" AS
				 SELECT "Name", "ID", "Defaulted", "Slug", "Notes" FROM "Vehicle"`,
				`CREATE TABLE "CompositeKey" (
					"TenantID" integer NOT NULL,
					"ItemID" integer NOT NULL,
					"Payload" text,
					PRIMARY KEY ("TenantID", "ItemID")
				)`,
			},
		},
		{
			name:       dialect.MySQL,
			driverName: dialect.MySQL,
			dsn:        requiredDSN("SQLTOM_MYSQL_DSN"),
			backend:    mysql.New(),
			schema:     "sqltom_test",
			selectRow:  "SELECT Name, Defaulted, Slug, Notes FROM Vehicle WHERE ID = ?",
			setup: []string{
				"DROP VIEW IF EXISTS VehicleView",
				"DROP TABLE IF EXISTS Vehicle",
				"DROP TABLE IF EXISTS CompositeKey",
				`CREATE TABLE Vehicle (
					Name varchar(100) NOT NULL,
					ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
					Defaulted varchar(100) DEFAULT 'default',
					Slug varchar(100) GENERATED ALWAYS AS (lower(Name)) STORED,
					Notes varchar(100)
				)`,
				`CREATE VIEW VehicleView AS
				 SELECT Name, ID, Defaulted, Slug, Notes FROM Vehicle`,
				`CREATE TABLE CompositeKey (
					TenantID integer NOT NULL,
					ItemID integer NOT NULL,
					Payload varchar(100),
					PRIMARY KEY (TenantID, ItemID)
				)`,
			},
		},
		{
			name:       dialect.SQLite,
			driverName: dialect.SQLite,
			dsn:        sqliteFilename,
			backend:    sqlite.New(),
			schema:     "main",
			selectRow:  `SELECT "Name", "Defaulted", "Slug", "Notes" FROM "main"."Vehicle" WHERE "ID" = ?`,
			setup: []string{
				`DROP VIEW IF EXISTS VehicleView`,
				`DROP TABLE IF EXISTS Vehicle`,
				`DROP TABLE IF EXISTS CompositeKey`,
				`CREATE TABLE Vehicle (
					Name TEXT NOT NULL,
					ID INTEGER PRIMARY KEY AUTOINCREMENT,
					Defaulted TEXT DEFAULT 'default',
					Slug TEXT GENERATED ALWAYS AS (lower(Name)) STORED,
					Notes TEXT
				)`,
				`CREATE VIEW VehicleView AS
				 SELECT Name, ID, Defaulted, Slug, Notes FROM Vehicle`,
				`CREATE TABLE CompositeKey (
					TenantID INTEGER NOT NULL,
					ItemID INTEGER NOT NULL,
					Payload TEXT,
					PRIMARY KEY (TenantID, ItemID)
				)`,
			},
		},
	}

	available := fixtures[:0]
	for _, current := range fixtures {
		if current.dsn != "" {
			available = append(available, current)
		}
	}
	return available
}

func prepareSQLServerDatabase(t *testing.T, ctx context.Context, dsn string) {
	t.Helper()
	if dsn == "" {
		t.Fatal("SQLTOM_SQLSERVER_ADMIN_DSN is required when SQLTOM_SQLSERVER_DSN is set")
	}
	db := openDatabase(t, ctx, dialect.SQLServer, dsn)
	defer db.Close()
	if _, err := db.ExecContext(ctx, `IF DB_ID(N'sqltom_test') IS NULL CREATE DATABASE [sqltom_test]`); err != nil {
		t.Fatalf("create SQL Server integration database: %v", err)
	}
}

func prepareSchema(t *testing.T, ctx context.Context, current fixture) {
	t.Helper()
	db := openDatabase(t, ctx, current.driverName, current.dsn)
	defer db.Close()
	requireTestDatabase(t, ctx, db, current.name)
	for _, statement := range current.setup {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			t.Fatalf("prepare %s schema with %q: %v", current.name, statement, err)
		}
	}
}

func requireTestDatabase(t *testing.T, ctx context.Context, db *sql.DB, dialectName string) {
	t.Helper()
	if dialectName == dialect.SQLite {
		return
	}
	query := ""
	switch dialectName {
	case dialect.SQLServer:
		query = `SELECT DB_NAME()`
	case dialect.Postgres:
		query = `SELECT current_database()`
	case dialect.MySQL:
		query = `SELECT DATABASE()`
	default:
		t.Fatalf("cannot verify integration database for unknown dialect %q", dialectName)
	}
	var databaseName string
	if err := db.QueryRowContext(ctx, query).Scan(&databaseName); err != nil {
		t.Fatalf("verify %s integration database: %v", dialectName, err)
	}
	if databaseName != "sqltom_test" {
		t.Fatalf("refusing destructive %s integration setup in database %q; expected %q", dialectName, databaseName, "sqltom_test")
	}
}

func openDatabase(t *testing.T, ctx context.Context, driverName, dsn string) *sql.DB {
	t.Helper()
	db, err := sql.Open(driverName, dsn)
	if err != nil {
		t.Fatal(err)
	}
	deadline := time.Now().Add(90 * time.Second)
	for {
		err = db.PingContext(ctx)
		if err == nil {
			return db
		}
		if time.Now().After(deadline) || ctx.Err() != nil {
			db.Close()
			t.Fatalf("connect using driver %s: %v", driverName, err)
		}
		time.Sleep(time.Second)
	}
}

func assertCommonManifest(t *testing.T, document *manifest.Manifest, current fixture) {
	t.Helper()
	if err := manifest.ValidateStructure(document); err != nil {
		t.Fatalf("manifest validation: %v", err)
	}
	if len(document.Tables) != 3 {
		t.Fatalf("tables = %d, want CompositeKey, Vehicle, and VehicleView", len(document.Tables))
	}
	table := findTable(t, document, current.schema, "Vehicle")
	if table.TableType != "BASE TABLE" || !table.IsManaged || len(table.Columns) != 5 {
		t.Fatalf("Vehicle metadata = %#v", table)
	}
	assertTableIdentity(t, document, table, current)
	view := findTable(t, document, current.schema, "VehicleView")
	if view.TableType != "VIEW" || !view.IsManaged || len(view.Columns) != 5 {
		t.Fatalf("VehicleView metadata = %#v", view)
	}
	assertTableIdentity(t, document, view, current)

	expectedGeneratedAlways := current.name != dialect.SQLServer
	wantColumns := []manifest.Column{
		{ColumnName: "Name", OrdinalPosition: 1, DataType: manifest.DataTypeString},
		{ColumnName: "ID", OrdinalPosition: 2, DataType: manifest.DataTypeInteger, IsIdentity: true, IsPrimaryKey: true, PrimaryKeyOrdinal: 1},
		{ColumnName: "Defaulted", OrdinalPosition: 3, IsNullable: true, DataType: manifest.DataTypeString, HasDefault: true},
		{ColumnName: "Slug", OrdinalPosition: 4, IsNullable: true, DataType: manifest.DataTypeString, IsComputed: true, IsGeneratedAlways: expectedGeneratedAlways},
		{ColumnName: "Notes", OrdinalPosition: 5, IsNullable: true, DataType: manifest.DataTypeString},
	}
	for _, want := range wantColumns {
		if got := findColumn(t, table, want.ColumnName); got != want {
			t.Errorf("%s Vehicle.%s metadata = %#v, want %#v", current.name, want.ColumnName, got, want)
		}
	}

	for ordinal, name := range []string{"Name", "ID", "Defaulted", "Slug", "Notes"} {
		column := findColumn(t, view, name)
		if column.ColumnName != name || column.OrdinalPosition != ordinal+1 || column.DataType != wantColumns[ordinal].DataType ||
			column.IsIdentity || column.IsPrimaryKey || column.IsComputed || column.IsGeneratedAlways || column.IsRowVersion || column.HasDefault || column.PrimaryKeyOrdinal != 0 {
			t.Errorf("%s VehicleView.%s metadata = %#v", current.name, name, column)
		}
	}

	composite := findTable(t, document, current.schema, "CompositeKey")
	if composite.TableType != "BASE TABLE" || !composite.IsManaged || len(composite.Columns) != 3 {
		t.Fatalf("CompositeKey metadata = %#v", composite)
	}
	assertTableIdentity(t, document, composite, current)
	for _, want := range []manifest.Column{
		{ColumnName: "TenantID", OrdinalPosition: 1, DataType: manifest.DataTypeInteger, IsPrimaryKey: true, PrimaryKeyOrdinal: 1},
		{ColumnName: "ItemID", OrdinalPosition: 2, DataType: manifest.DataTypeInteger, IsPrimaryKey: true, PrimaryKeyOrdinal: 2},
		{ColumnName: "Payload", OrdinalPosition: 3, IsNullable: true, DataType: manifest.DataTypeString},
	} {
		if got := findColumn(t, composite, want.ColumnName); got != want {
			t.Errorf("%s CompositeKey.%s metadata = %#v, want %#v", current.name, want.ColumnName, got, want)
		}
	}
}

func assertTableIdentity(t *testing.T, document *manifest.Manifest, table manifest.Table, current fixture) {
	t.Helper()
	wantCatalog := document.DatabaseName
	if current.name == dialect.MySQL {
		wantCatalog = "def"
	}
	if table.TableCatalog != wantCatalog || table.TableSchema != current.schema {
		t.Errorf("%s table %s identity = catalog %q, schema %q; want catalog %q, schema %q", current.name, table.TableName, table.TableCatalog, table.TableSchema, wantCatalog, current.schema)
	}
}

func assertCommonRenderedWrites(t *testing.T, filename string) {
	t.Helper()
	insert := generatedFunction(t, filename, "Insert")
	update := generatedFunction(t, filename, "Update")
	for _, field := range []string{"Name", "Defaulted", "Notes"} {
		if !strings.Contains(insert, "r."+field) || !strings.Contains(update, "r."+field) {
			t.Errorf("writable field %s is missing from Insert or Update", field)
		}
	}
	if strings.Contains(insert, "Slug") || strings.Contains(update, "Slug") {
		t.Error("computed field Slug is present in Insert or Update")
	}
}

func executeCommonRenderedWrites(t *testing.T, ctx context.Context, current fixture, filename string) {
	t.Helper()
	insertQuery := generatedQuery(t, filename, "Insert")
	updateQuery := generatedQuery(t, filename, "Update")
	db := openDatabase(t, ctx, current.driverName, current.dsn)
	defer db.Close()

	var id int64
	if current.returnsID {
		if err := db.QueryRowContext(ctx, insertQuery, "Initial", "explicit", "notes").Scan(&id); err != nil {
			t.Fatalf("%s generated insert: %v\n%s", current.name, err, insertQuery)
		}
	} else {
		result, err := db.ExecContext(ctx, insertQuery, "Initial", "explicit", "notes")
		if err != nil {
			t.Fatalf("%s generated insert: %v\n%s", current.name, err, insertQuery)
		}
		id, err = result.LastInsertId()
		if err != nil {
			t.Fatalf("%s LastInsertId: %v", current.name, err)
		}
	}

	if _, err := db.ExecContext(ctx, updateQuery, "Updated", "changed", "updated notes", id); err != nil {
		t.Fatalf("%s generated update: %v\n%s", current.name, err, updateQuery)
	}

	var name, defaulted, slug, notes string
	if err := db.QueryRowContext(ctx, current.selectRow, id).Scan(&name, &defaulted, &slug, &notes); err != nil {
		t.Fatalf("%s verify generated writes: %v", current.name, err)
	}
	if name != "Updated" || defaulted != "changed" || slug != "updated" || notes != "updated notes" {
		t.Fatalf("%s written row = (%q, %q, %q, %q)", current.name, name, defaulted, slug, notes)
	}
}

func assertPostgresDomainDefault(t *testing.T, ctx context.Context, current fixture) {
	t.Helper()
	db := openDatabase(t, ctx, current.driverName, current.dsn)
	defer db.Close()
	requireTestDatabase(t, ctx, db, current.name)

	for _, statement := range []string{
		`DROP TABLE IF EXISTS "DomainDefault"`,
		`DROP DOMAIN IF EXISTS "TextWithDefault"`,
		`CREATE DOMAIN "TextWithDefault" AS text DEFAULT 'domain default'`,
		`CREATE TABLE "DomainDefault" ("Value" "TextWithDefault")`,
	} {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			t.Fatalf("prepare PostgreSQL domain default with %q: %v", statement, err)
		}
	}

	inspection, err := current.backend.Inspect(ctx, current.dsn)
	if err != nil {
		t.Fatalf("inspect PostgreSQL domain default: %v", err)
	}
	table := findTable(t, inspection.Manifest, current.schema, "DomainDefault")
	column := findColumn(t, table, "Value")
	if !column.HasDefault {
		t.Fatalf("PostgreSQL domain default metadata = %#v", column)
	}
}

func findTable(t *testing.T, document *manifest.Manifest, schema, name string) manifest.Table {
	t.Helper()
	for _, table := range document.Tables {
		if table.TableSchema == schema && table.TableName == name {
			return table
		}
	}
	t.Fatalf("table %s.%s not found", schema, name)
	return manifest.Table{}
}

func findColumn(t *testing.T, table manifest.Table, name string) manifest.Column {
	t.Helper()
	for _, column := range table.Columns {
		if column.ColumnName == name {
			return column
		}
	}
	t.Fatalf("column %s.%s not found", table.TableName, name)
	return manifest.Column{}
}

func generatedFunction(t *testing.T, filename, name string) string {
	t.Helper()
	data, err := os.ReadFile(filename)
	if err != nil {
		t.Fatal(err)
	}
	files := token.NewFileSet()
	file, err := parser.ParseFile(files, filename, data, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse %s: %v", filename, err)
	}
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name.Name != name {
			continue
		}
		start := files.Position(function.Pos()).Offset
		end := files.Position(function.End()).Offset
		return string(data[start:end])
	}
	t.Fatalf("generated function %s not found in %s", name, filename)
	return ""
}

func generatedQuery(t *testing.T, filename, functionName string) string {
	t.Helper()
	data, err := os.ReadFile(filename)
	if err != nil {
		t.Fatal(err)
	}
	files := token.NewFileSet()
	file, err := parser.ParseFile(files, filename, data, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse %s: %v", filename, err)
	}
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name.Name != functionName {
			continue
		}
		var query string
		var found bool
		ast.Inspect(function.Body, func(node ast.Node) bool {
			specification, ok := node.(*ast.ValueSpec)
			if !ok {
				return true
			}
			for index, name := range specification.Names {
				if name.Name != "query" || index >= len(specification.Values) {
					continue
				}
				query, found = constantString(specification.Values[index])
				return false
			}
			return true
		})
		if !found {
			t.Fatalf("constant query not found in generated function %s", functionName)
		}
		return query
	}
	t.Fatalf("generated function %s not found in %s", functionName, filename)
	return ""
}

func constantString(expression ast.Expr) (string, bool) {
	switch value := expression.(type) {
	case *ast.BasicLit:
		if value.Kind != token.STRING {
			return "", false
		}
		unquoted, err := strconv.Unquote(value.Value)
		return unquoted, err == nil
	case *ast.BinaryExpr:
		if value.Op != token.ADD {
			return "", false
		}
		left, leftOK := constantString(value.X)
		right, rightOK := constantString(value.Y)
		return left + right, leftOK && rightOK
	case *ast.ParenExpr:
		return constantString(value.X)
	default:
		return "", false
	}
}
